name: initiative
description: Initiative App
publish_to: 'none'

version: 1.3.0+8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  collection: ^1.17.2
  shared_preferences: ^2.2.1
  flutter_speed_dial: ^7.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  # see https://flutter.io/assets-and-images/#resolution-aware.
  # see https://flutter.io/assets-and-images/#from-packages
