# see https://www.dartlang.org/tools/pub/pubspec

name: initiative
description: Initiative App

version: 1.2.4+6

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^1.2.4
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.4+5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  # see https://flutter.io/assets-and-images/#resolution-aware.
  # see https://flutter.io/assets-and-images/#from-packages
